version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
  create-minio-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/photo-library;
      /usr/bin/mc anonymous set public myminio/photo-library;
      exit 0;
      "
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  photo-library-frontend:
    image: ucostantini/photo-library-frontend:latest
    depends_on:
      - photo-library-backend
    ports:
      - 4200:4200
  photo-library-backend:
    image: ucostantini/photo-library-backend:latest
    depends_on:
      - minio-create-bucket
      - elasticsearch
    environment:
      DB_CLIENT: "sqlite"
      DB_PATH: "/app/db.sqlite"
      ELASTIC_ENDPOINT: "http://elasticsearch:9200"
      STORAGE_SERVICE: "minio"
      MINIO_ENDPOINT: "minio"
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_USE_SSL: "false"
      MINIO_BUCKET_NAME: "photo-library"
      LOG_LEVEL: "info"
    ports:
      - 3000:3000
volumes:
  minio-data: {}
  elasticsearch-data:
    driver: local
