name: Photo-Library CI/CD
on:
    push:
jobs:
    frontend:
        name: Build and Deploy Frontend docker image
        runs-on: ubuntu-latest
        container:
            image: 'lucasalt/act_base:latest'
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: 'karushifaa'
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./client
                file: ./client/Dockerfile
                push: true
                tags: 'karushifaa/photo-library-frontend:latest'
    backend:
        name: Build and Deploy Backend docker image
        runs-on: ubuntu-latest
        container:
            image: 'lucasalt/act_base:latest'
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: 'karushifaa'
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./server
                file: ./server/Dockerfile
                push: true
                tags: 'karushifaa/photo-library-backend:latest'
